# Generated by Django 4.2.3 on 2023-07-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_chosen_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Phone_Number',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
