# Generated by Django 4.2.3 on 2023-07-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_choosen_time'),
        ('booking', '0004_appointment_phone_number'),
    ]

    operations = [
    ]
