# Generated by Django 4.2.3 on 2023-07-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_merge_20230725_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Phone_Number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='chosen_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='reference',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
